name: test and build web application

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: 
      - self-hosted
      - Kumojin-web-app
    strategy:
      matrix:
        node-version: ['20']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'package-lock.json'
    - run: npm ci
      working-directory: ../Frontend/kumojimEvents
    - name: run unit test
      working-directory: ../Frontend/kumojimEvents
    - run: npm run test
      working-directory: ../Frontend/kumojimEvents
    - run: npm run build --if-present
      working-directory: ../Frontend/kumojimEvents
    - run: npm test
      working-directory: ../Frontend/kumojimEvents
    - name: Build Docker image for web application
    - run: docker build . --file Dockerfile --tag kumojin-app:$(date +%s)
      working-directory: ../Frontend/kumojimEvents
