name: test and build web application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./Frontend/KumojimEvents
    strategy:
      matrix:
        node-version: ['20.13.1']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --force
    - name: run unit test
      run: npm run test
    - run: npm run build --if-present
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: where mi
      run : ls -l /home/runner/work/kumojinEvent/kumojinEvent/
    - name: Build and push Docker image
      run: docker build . -t kumojin-app:latest
    - name: push to docker hub
      run: |
        docker tag kumojin-app:latest  bhazied/kumojin-app:latest
        docker push bhazied/kumojin-app:latest
      
  deploy:
    needs: [ test, build ]
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./deploy
    steps:
    - name: deploy
      run: docker images
  
